blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/daigotanaka0714/image-crunch/discussions/categories/ideas
    about: Please suggest new feature ideas in Discussions
